version: '3.8'
services:
  frontend:
    image: ghcr.io/minglarn/batvader-frontend:latest
    ports:
      - "8090:80"
    depends_on:
      - backend

  backend:
    image: ghcr.io/minglarn/batvader-backend:latest
    ports:
      - "8000:8000"
    volumes:
      - sqlite_data:/app/data

volumes:
  sqlite_data:
