# version: '3.8'
services:
  frontend:
    image: ghcr.io/minglarn/batvader-frontend:latest
    environment:
      - TZ=Europe/Stockholm
    ports:
      - "8090:80"
    depends_on:
      - backend

  backend:
    image: ghcr.io/minglarn/batvader-backend:latest
    container_name: batliv
    environment:
      - TZ=Europe/Stockholm
      - PYTHONUNBUFFERED=1
      - PYTHONIOENCODING=utf-8
      - LMSTUDIO_URL=http://192.168.1.239:11434/api/v0
      - LMSTUDIO_MODEL=qwen/qwen3.5-9b
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
